
heroes = [
    "abaddon",
    "alchemist",
    "ancient-apparition",
    "anti-mage",
    "arc-warden",
    "axe",
    "bane",
    "batrider",
    "beastmaster",
    "bloodseeker",
    "bounty-hunter",
    "brewmaster",
    "bristleback",
    "broodmother",
    "centaur-warrunner",
    "chaos-knight",
    "chen",
    "clinkz",
    "clockwerk",
    "crystal-maiden",
    "dark-seer",
    "dark-willow",
    "dazzle",
    "death-prophet",
    "disruptor",
    "doom",
    "dragon-knight",
    "drow-ranger",
    "earth-spirit",
    "earthshaker",
    "elder-titan",
    "ember-spirit",
    "enchantress",
    "enigma",
    "faceless-void",
    "grimstroke",
    "gyrocopter",
    "huskar",
    "invoker",
    "io",
    "jakiro",
    "juggernaut",
    "keeper-of-the-light",
    "kunkka",
    "legion-commander",
    "leshrac",
    "lich",
    "lifestealer",
    "lina",
    "lion",
    "lone-druid",
    "luna",
    "lycan",
    "magnus",
    "mars",
    "medusa",
    "meepo",
    "mirana",
    "monkey-king",
    "morphling",
    "naga-siren",
    "natures-prophet",
    "necrophos",
    "night-stalker",
    "nyx-assassin",
    "ogre-magi",
    "omniknight",
    "oracle",
    "outworld-devourer",
    "pangolier",
    "phantom-assassin",
    "phantom-lancer",
    "phoenix",
    "puck",
    "pudge",
    "pugna",
    "queen-of-pain",
    "razor",
    "riki",
    "rubick",
    "sand-king",
    "shadow-demon",
    "shadow-fiend",
    "shadow-shaman",
    "silencer",
    "skywrath-mage",
    "slardar",
    "slark",
    "snapfire",
    "sniper",
    "spectre",
    "spirit-breaker",
    "storm-spirit",
    "sven",
    "techies",
    "templar-assassin",
    "terrorblade",
    "tidehunter",
    "timbersaw",
    "tinker",
    "tiny",
    "treant-protector",
    "troll-warlord",
    "tusk",
    "underlord",
    "undying",
    "ursa",
    "vengeful-spirit",
    "venomancer",
    "viper",
    "visage",
    "void-spirit",
    "warlock",
    "weaver",
    "windranger",
    "winter-wyvern",
    "witch-doctor",
    "wraith-king",
    "zeus",
];

heroesLinks = {
    "abaddon" : "https://www.dotabuff.com/heroes/abaddon",
    "alchemist" : "https://www.dotabuff.com/heroes/alchemist",
    "ancient-apparition" : "https://www.dotabuff.com/heroes/ancient-apparition",
    "anti-mage" : "https://www.dotabuff.com/heroes/anti-mage",
    "arc-warden" : "https://www.dotabuff.com/heroes/arc-warden",
    "axe" : "https://www.dotabuff.com/heroes/axe",
    "bane" : "https://www.dotabuff.com/heroes/bane",
    "batrider" : "https://www.dotabuff.com/heroes/batrider",
    "beastmaster" : "https://www.dotabuff.com/heroes/beastmaster",
    "bloodseeker" : "https://www.dotabuff.com/heroes/bloodseeker",
    "bounty-hunter" : "https://www.dotabuff.com/heroes/bounty-hunter",
    "brewmaster" : "https://www.dotabuff.com/heroes/brewmaster",
    "bristleback" : "https://www.dotabuff.com/heroes/bristleback",
    "broodmother" : "https://www.dotabuff.com/heroes/broodmother",
    "centaur-warrunner" : "https://www.dotabuff.com/heroes/centaur-warrunner",
    "chaos-knight" : "https://www.dotabuff.com/heroes/chaos-knight",
    "chen" : "https://www.dotabuff.com/heroes/chen",
    "clinkz" : "https://www.dotabuff.com/heroes/clinkz",
    "clockwerk" : "https://www.dotabuff.com/heroes/clockwerk",
    "crystal-maiden" : "https://www.dotabuff.com/heroes/crystal-maiden",
    "dark-seer" : "https://www.dotabuff.com/heroes/dark-seer",
    "dark-willow" : "https://www.dotabuff.com/heroes/dark-willow",
    "dazzle" : "https://www.dotabuff.com/heroes/dazzle",
    "death-prophet" : "https://www.dotabuff.com/heroes/death-prophet",
    "disruptor" : "https://www.dotabuff.com/heroes/disruptor",
    "doom" : "https://www.dotabuff.com/heroes/doom",
    "dragon-knight" : "https://www.dotabuff.com/heroes/dragon-knight",
    "drow-ranger" : "https://www.dotabuff.com/heroes/drow-ranger",
    "earth-spirit" : "https://www.dotabuff.com/heroes/earth-spirit",
    "earthshaker" : "https://www.dotabuff.com/heroes/earthshaker",
    "elder-titan" : "https://www.dotabuff.com/heroes/elder-titan",
    "ember-spirit" : "https://www.dotabuff.com/heroes/ember-spirit",
    "enchantress" : "https://www.dotabuff.com/heroes/enchantress",
    "enigma" : "https://www.dotabuff.com/heroes/enigma",
    "faceless-void" : "https://www.dotabuff.com/heroes/faceless-void",
    "grimstroke" : "https://www.dotabuff.com/heroes/grimstroke",
    "gyrocopter" : "https://www.dotabuff.com/heroes/gyrocopter",
    "huskar" : "https://www.dotabuff.com/heroes/huskar",
    "invoker" : "https://www.dotabuff.com/heroes/invoker",
    "io" : "https://www.dotabuff.com/heroes/io",
    "jakiro" : "https://www.dotabuff.com/heroes/jakiro",
    "juggernaut" : "https://www.dotabuff.com/heroes/juggernaut",
    "keeper-of-the-light" : "https://www.dotabuff.com/heroes/keeper-of-the-light",
    "kunkka" : "https://www.dotabuff.com/heroes/kunkka",
    "legion-commander" : "https://www.dotabuff.com/heroes/legion-commander",
    "leshrac" : "https://www.dotabuff.com/heroes/leshrac",
    "lich" : "https://www.dotabuff.com/heroes/lich",
    "lifestealer" : "https://www.dotabuff.com/heroes/lifestealer",
    "lina" : "https://www.dotabuff.com/heroes/lina",
    "lion" : "https://www.dotabuff.com/heroes/lion",
    "lone-druid" : "https://www.dotabuff.com/heroes/lone-druid",
    "luna" : "https://www.dotabuff.com/heroes/luna",
    "lycan" : "https://www.dotabuff.com/heroes/lycan",
    "magnus" : "https://www.dotabuff.com/heroes/magnus",
    "mars" : "https://www.dotabuff.com/heroes/mars",
    "medusa" : "https://www.dotabuff.com/heroes/medusa",
    "meepo" : "https://www.dotabuff.com/heroes/meepo",
    "mirana" : "https://www.dotabuff.com/heroes/mirana",
    "monkey-king" : "https://www.dotabuff.com/heroes/monkey-king",
    "morphling" : "https://www.dotabuff.com/heroes/morphling",
    "naga-siren" : "https://www.dotabuff.com/heroes/naga-siren",
    "natures-prophet" : "https://www.dotabuff.com/heroes/natures-prophet",
    "necrophos" : "https://www.dotabuff.com/heroes/necrophos",
    "night-stalker" : "https://www.dotabuff.com/heroes/night-stalker",
    "nyx-assassin" : "https://www.dotabuff.com/heroes/nyx-assassin",
    "ogre-magi" : "https://www.dotabuff.com/heroes/ogre-magi",
    "omniknight" : "https://www.dotabuff.com/heroes/omniknight",
    "oracle" : "https://www.dotabuff.com/heroes/oracle",
    "outworld-devourer" : "https://www.dotabuff.com/heroes/outworld-devourer",
    "pangolier" : "https://www.dotabuff.com/heroes/pangolier",
    "phantom-assassin" : "https://www.dotabuff.com/heroes/phantom-assassin",
    "phantom-lancer" : "https://www.dotabuff.com/heroes/phantom-lancer",
    "phoenix" : "https://www.dotabuff.com/heroes/phoenix",
    "puck" : "https://www.dotabuff.com/heroes/puck",
    "pudge" : "https://www.dotabuff.com/heroes/pudge",
    "pugna" : "https://www.dotabuff.com/heroes/pugna",
    "queen-of-pain" : "https://www.dotabuff.com/heroes/queen-of-pain",
    "razor" : "https://www.dotabuff.com/heroes/razor",
    "riki" : "https://www.dotabuff.com/heroes/riki",
    "rubick" : "https://www.dotabuff.com/heroes/rubick",
    "sand-king" : "https://www.dotabuff.com/heroes/sand-king",
    "shadow-demon" : "https://www.dotabuff.com/heroes/shadow-demon",
    "shadow-fiend" : "https://www.dotabuff.com/heroes/shadow-fiend",
    "shadow-shaman" : "https://www.dotabuff.com/heroes/shadow-shaman",
    "silencer" : "https://www.dotabuff.com/heroes/silencer",
    "skywrath-mage" : "https://www.dotabuff.com/heroes/skywrath-mage",
    "slardar" : "https://www.dotabuff.com/heroes/slardar",
    "slark" : "https://www.dotabuff.com/heroes/slark",
    "snapfire" : "https://www.dotabuff.com/heroes/snapfire",
    "sniper" : "https://www.dotabuff.com/heroes/sniper",
    "spectre" : "https://www.dotabuff.com/heroes/spectre",
    "spirit-breaker" : "https://www.dotabuff.com/heroes/spirit-breaker",
    "storm-spirit" : "https://www.dotabuff.com/heroes/storm-spirit",
    "sven" : "https://www.dotabuff.com/heroes/sven",
    "techies" : "https://www.dotabuff.com/heroes/techies",
    "templar-assassin" : "https://www.dotabuff.com/heroes/templar-assassin",
    "terrorblade" : "https://www.dotabuff.com/heroes/terrorblade",
    "tidehunter" : "https://www.dotabuff.com/heroes/tidehunter",
    "timbersaw" : "https://www.dotabuff.com/heroes/timbersaw",
    "tinker" : "https://www.dotabuff.com/heroes/tinker",
    "tiny" : "https://www.dotabuff.com/heroes/tiny",
    "treant-protector" : "https://www.dotabuff.com/heroes/treant-protector",
    "troll-warlord" : "https://www.dotabuff.com/heroes/troll-warlord",
    "tusk" : "https://www.dotabuff.com/heroes/tusk",
    "underlord" : "https://www.dotabuff.com/heroes/underlord",
    "undying" : "https://www.dotabuff.com/heroes/undying",
    "ursa" : "https://www.dotabuff.com/heroes/ursa",
    "vengeful-spirit" : "https://www.dotabuff.com/heroes/vengeful-spirit",
    "venomancer" : "https://www.dotabuff.com/heroes/venomancer",
    "viper" : "https://www.dotabuff.com/heroes/viper",
    "visage" : "https://www.dotabuff.com/heroes/visage",
    "void-spirit" : "https://www.dotabuff.com/heroes/void-spirit",
    "warlock" : "https://www.dotabuff.com/heroes/warlock",
    "weaver" : "https://www.dotabuff.com/heroes/weaver",
    "windranger" : "https://www.dotabuff.com/heroes/windranger",
    "winter-wyvern" : "https://www.dotabuff.com/heroes/winter-wyvern",
    "witch-doctor" : "https://www.dotabuff.com/heroes/witch-doctor",
    "wraith-king" : "https://www.dotabuff.com/heroes/wraith-king",
    "zeus" : "https://www.dotabuff.com/heroes/zeus"
};